### ISSUE TITLE
AVIFが処理できずエラーを吐く

### ISSUE THREAD

**Issue by AmaseCocoa** [AmaseCocoa/media-proxy#4]
Windowsだけかも

libheifが無いだけの可能性もある
```
Error processing image: Traceback (most recent call last):
  File "D:\media-proxy\server.py", line 143, in proxy_image
    save_image(img, img_output, image_format)
  File "D:\media-proxy\server.py", line 156, in save_image
    buffer = image.write_to_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\media-proxy\.venv\Lib\site-packages\pyvips\vimage.py", line 865, in write_to_buffer
    pyvips.Operation.call(name, self, target,
  File "d:\media-proxy\.venv\Lib\site-packages\pyvips\voperation.py", line 305, in call       
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call VipsForeignSaveWebpTarget
  source: bad seek to 92115
heif: Invalid input: Unspecified: Bitstream not supported by this decoder (2.0)
```

**Comment by AmaseCocoa** [comment]
Docker版だと動くから単純にlibheifが入ってないだけだと思う
